/**
 * Exact column layout of the client's MSSA master workbook, extracted from
 * the file itself — headers, column letters, and the dominant formula each
 * computed column carries (e.g. Outstanding = Amount - Paid). Regenerating
 * requires the original workbook; this is committed as static data because
 * the layout does not change bike to bike.
 *
 * `formula` templates use {R} for the current row number and are otherwise
 * exact Excel formula text (no leading "="), e.g. "AM{R}-AN{R}" ->
 * =AM12-AN12 on row 12. Column letters in a formula refer to THIS sheet's
 * own columns, which is only valid because the export reproduces the
 * source workbook's column order exactly.
 *
 * `dbField` names match NormalizedRow / salvage_bikes columns 1:1 — set
 * only on the single column that "owns" that field, resolved the same way
 * the importer resolves duplicate headers (most-populated column wins),
 * so a near-empty duplicate column (e.g. "Retails" next to "Retail", or
 * "Insurance Amount" next to "Insurance Amount inc VAT") is not silently
 * filled with data that never lived there.
 */

export type ColumnKind = "field" | "formula" | "ledger";

export type MasterColumn = {
  /** 0-based column index, matching the source workbook exactly. */
  index: number;
  /** Excel column letter, e.g. "AM". */
  letter: string;
  /** Header text exactly as it appears in the client's file. */
  header: string;
  kind: ColumnKind;
  /** Present when kind === "formula". {R} is the row placeholder. */
  formula: string | null;
  /** Present when kind === "field". A NormalizedRow / bike DB field name. */
  dbField: string | null;
};


export const BRYTE_HOLLARD_COLUMNS: MasterColumn[] = [
  { index: 0, letter: "A", header: "ktm", kind: "ledger", formula: null, dbField: null },
  { index: 1, letter: "B", header: "Stock No", kind: "field", formula: null, dbField: "stock_number" },
  { index: 2, letter: "C", header: "Stock Take", kind: "ledger", formula: null, dbField: null },
  { index: 3, letter: "D", header: "Claim No", kind: "field", formula: null, dbField: "claim_number" },
  { index: 4, letter: "E", header: "Insurance Company", kind: "field", formula: null, dbField: "insurance_company" },
  { index: 5, letter: "F", header: "Broker", kind: "field", formula: null, dbField: "broker" },
  { index: 6, letter: "G", header: "Month", kind: "ledger", formula: null, dbField: null },
  { index: 7, letter: "H", header: "Date", kind: "field", formula: null, dbField: "loss_date" },
  { index: 8, letter: "I", header: "Date today", kind: "formula", formula: "TODAY()", dbField: null },
  { index: 9, letter: "J", header: "Days Open", kind: "formula", formula: "NETWORKDAYS(H{R},I{R})", dbField: null },
  { index: 10, letter: "K", header: "Claims Handler", kind: "field", formula: null, dbField: "claims_handler" },
  { index: 11, letter: "L", header: "Salvage Clerk", kind: "field", formula: null, dbField: "salvage_clerk" },
  { index: 12, letter: "M", header: "Make", kind: "field", formula: null, dbField: "make" },
  { index: 13, letter: "N", header: "Model", kind: "field", formula: null, dbField: "model" },
  { index: 14, letter: "O", header: "CC", kind: "field", formula: null, dbField: "engine_capacity_cc" },
  { index: 15, letter: "P", header: "Year", kind: "field", formula: null, dbField: "year" },
  { index: 16, letter: "Q", header: "Keys", kind: "field", formula: null, dbField: "keys_status" },
  { index: 17, letter: "R", header: "Vin Number", kind: "field", formula: null, dbField: "vin_number" },
  { index: 18, letter: "S", header: "Engine Number", kind: "field", formula: null, dbField: "engine_number" },
  { index: 19, letter: "T", header: "Number Plate", kind: "field", formula: null, dbField: "registration_number" },
  { index: 20, letter: "U", header: "Write Off code", kind: "field", formula: null, dbField: "write_off_code" },
  { index: 21, letter: "V", header: "WEBSITE", kind: "ledger", formula: null, dbField: null },
  { index: 22, letter: "W", header: "Commision", kind: "formula", formula: "AK{R}", dbField: null },
  { index: 23, letter: "X", header: "Total comms INCL VAT", kind: "formula", formula: "SUM(W{R}:W{R})*1.15", dbField: null },
  { index: 24, letter: "Y", header: "INSURANCE INV to MSSA", kind: "formula", formula: "AB{R}-X{R}", dbField: null },
  { index: 25, letter: "Z", header: "Insurance Return after comms", kind: "formula", formula: "Y{R}/AJ{R}", dbField: null },
  { index: 26, letter: "AA", header: "Insurance Amount Exc VAT", kind: "formula", formula: "AB{R}/1.15", dbField: null },
  { index: 27, letter: "AB", header: "Insurance Amount inc VAT", kind: "field", formula: null, dbField: "insurance_amount" },
  { index: 28, letter: "AC", header: "Transport", kind: "formula", formula: "CR{R}+CX{R}", dbField: null },
  { index: 29, letter: "AD", header: "Dealerstock", kind: "ledger", formula: null, dbField: null },
  { index: 30, letter: "AE", header: "Total Cost", kind: "formula", formula: "Y{R}+AD{R}+AC{R}", dbField: null },
  { index: 31, letter: "AF", header: "Selling Amount", kind: "formula", formula: "BG{R}", dbField: null },
  { index: 32, letter: "AG", header: "Profit", kind: "formula", formula: "AF{R}-AE{R}", dbField: null },
  { index: 33, letter: "AH", header: "Trade", kind: "ledger", formula: null, dbField: null },
  { index: 34, letter: "AI", header: "Retails", kind: "ledger", formula: null, dbField: null },
  { index: 35, letter: "AJ", header: "Retail", kind: "field", formula: null, dbField: "retail_value" },
  { index: 36, letter: "AK", header: "% Amount", kind: "formula", formula: "AB{R}*15%", dbField: null },
  { index: 37, letter: "AL", header: "Insurance Inv No", kind: "field", formula: null, dbField: "insurance_invoice_no" },
  { index: 38, letter: "AM", header: "Insurance Amount", kind: "ledger", formula: null, dbField: null },
  { index: 39, letter: "AN", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 40, letter: "AO", header: "Outstanding", kind: "formula", formula: "AM{R}-AN{R}", dbField: null },
  { index: 41, letter: "AP", header: "Inv Request Date", kind: "ledger", formula: null, dbField: null },
  { index: 42, letter: "AQ", header: "Total TAT from INV Request", kind: "formula", formula: "NETWORKDAYS(H{R},AP{R})", dbField: null },
  { index: 43, letter: "AR", header: "Inv received Date", kind: "ledger", formula: null, dbField: null },
  { index: 44, letter: "AS", header: "Total TAT from INV Received", kind: "formula", formula: "NETWORKDAYS(H{R},AR{R})", dbField: null },
  { index: 45, letter: "AT", header: "Days wait for INV", kind: "formula", formula: "AS{R}-AQ{R}", dbField: null },
  { index: 46, letter: "AU", header: "Date Paid", kind: "ledger", formula: null, dbField: null },
  { index: 47, letter: "AV", header: "Days to pay INV", kind: "formula", formula: "NETWORKDAYS(AR{R},AU{R})", dbField: null },
  { index: 48, letter: "AW", header: "Ins INV Paid", kind: "ledger", formula: null, dbField: null },
  { index: 49, letter: "AX", header: "Natis Docs", kind: "ledger", formula: null, dbField: null },
  { index: 50, letter: "AY", header: "Date Received", kind: "field", formula: null, dbField: "date_received" },
  { index: 51, letter: "AZ", header: "Insurance Paid", kind: "ledger", formula: null, dbField: null },
  { index: 52, letter: "BA", header: "Status", kind: "field", formula: null, dbField: "status" },
  { index: 53, letter: "BB", header: "Store", kind: "field", formula: null, dbField: "current_location" },
  { index: 54, letter: "BC", header: "Arrival Date", kind: "field", formula: null, dbField: "arrival_date" },
  { index: 55, letter: "BD", header: "TAT from Instruction to Del at MSSA", kind: "formula", formula: "NETWORKDAYS(H{R},BC{R})", dbField: null },
  { index: 56, letter: "BE", header: "Sold To", kind: "field", formula: null, dbField: "sold_to" },
  { index: 57, letter: "BF", header: "Month", kind: "ledger", formula: null, dbField: null },
  { index: 58, letter: "BG", header: "Selling Amount", kind: "ledger", formula: null, dbField: null },
  { index: 59, letter: "BH", header: "Deposit", kind: "ledger", formula: null, dbField: null },
  { index: 60, letter: "BI", header: "Total outstanding", kind: "formula", formula: "BG{R}-BH{R}", dbField: null },
  { index: 61, letter: "BJ", header: "INV no", kind: "ledger", formula: null, dbField: null },
  { index: 62, letter: "BK", header: "Receipt 1", kind: "ledger", formula: null, dbField: null },
  { index: 63, letter: "BL", header: "Receipt 2", kind: "ledger", formula: null, dbField: null },
  { index: 64, letter: "BM", header: "Receipt 3", kind: "ledger", formula: null, dbField: null },
  { index: 65, letter: "BN", header: "Receipt 4", kind: "ledger", formula: null, dbField: null },
  { index: 66, letter: "BO", header: "Release Creditor Invoice 1", kind: "ledger", formula: null, dbField: null },
  { index: 67, letter: "BP", header: "Invoice no", kind: "ledger", formula: null, dbField: null },
  { index: 68, letter: "BQ", header: "Inv Date", kind: "ledger", formula: null, dbField: null },
  { index: 69, letter: "BR", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 70, letter: "BS", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 71, letter: "BT", header: "Outstanding", kind: "formula", formula: "BR{R}-BS{R}", dbField: null },
  { index: 72, letter: "BU", header: "Release Creditor Invoice 2", kind: "ledger", formula: null, dbField: null },
  { index: 73, letter: "BV", header: "Invoice no", kind: "ledger", formula: null, dbField: null },
  { index: 74, letter: "BW", header: "Inv Date", kind: "ledger", formula: null, dbField: null },
  { index: 75, letter: "BX", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 76, letter: "BY", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 77, letter: "BZ", header: "Outstanding", kind: "ledger", formula: null, dbField: null },
  { index: 78, letter: "CA", header: "Insurance Release  Invoice no 1:", kind: "ledger", formula: null, dbField: null },
  { index: 79, letter: "CB", header: "Month", kind: "ledger", formula: null, dbField: null },
  { index: 80, letter: "CC", header: "Insurance Order no", kind: "ledger", formula: null, dbField: null },
  { index: 81, letter: "CD", header: "INS INV No MSSA", kind: "ledger", formula: null, dbField: null },
  { index: 82, letter: "CE", header: "INS Receipt no MSSA", kind: "ledger", formula: null, dbField: null },
  { index: 83, letter: "CF", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 84, letter: "CG", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 85, letter: "CH", header: "Outstanding", kind: "formula", formula: "CF{R}-CG{R}", dbField: null },
  { index: 86, letter: "CI", header: "Insurance Release   Invoice no 2:", kind: "ledger", formula: null, dbField: null },
  { index: 87, letter: "CJ", header: "Month", kind: "ledger", formula: null, dbField: null },
  { index: 88, letter: "CK", header: "MSSA INV No", kind: "ledger", formula: null, dbField: null },
  { index: 89, letter: "CL", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 90, letter: "CM", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 91, letter: "CN", header: "Outstanding", kind: "formula", formula: "CL{R}-CM{R}", dbField: null },
  { index: 92, letter: "CO", header: "Uplift Creditor 1", kind: "ledger", formula: null, dbField: null },
  { index: 93, letter: "CP", header: "Invoice no", kind: "ledger", formula: null, dbField: null },
  { index: 94, letter: "CQ", header: "Inv Date", kind: "ledger", formula: null, dbField: null },
  { index: 95, letter: "CR", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 96, letter: "CS", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 97, letter: "CT", header: "Outstanding", kind: "formula", formula: "CR{R}-CS{R}", dbField: null },
  { index: 98, letter: "CU", header: "Uplift Creditor 2", kind: "ledger", formula: null, dbField: null },
  { index: 99, letter: "CV", header: "Invoice no", kind: "ledger", formula: null, dbField: null },
  { index: 100, letter: "CW", header: "Inv Date", kind: "ledger", formula: null, dbField: null },
  { index: 101, letter: "CX", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 102, letter: "CY", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 103, letter: "CZ", header: "Outstanding", kind: "formula", formula: "CX{R}-CY{R}", dbField: null },
  { index: 104, letter: "DA", header: "InsuranceUpliftment 1  Invoice no:", kind: "ledger", formula: null, dbField: null },
  { index: 105, letter: "DB", header: "Month", kind: "ledger", formula: null, dbField: null },
  { index: 106, letter: "DC", header: "MSSA INV no", kind: "ledger", formula: null, dbField: null },
  { index: 107, letter: "DD", header: "MSSA Receipt no", kind: "ledger", formula: null, dbField: null },
  { index: 108, letter: "DE", header: "Insurance Order no", kind: "ledger", formula: null, dbField: null },
  { index: 109, letter: "DF", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 110, letter: "DG", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 111, letter: "DH", header: "Outstanding", kind: "formula", formula: "DF{R}-DG{R}", dbField: null },
  { index: 112, letter: "DI", header: "Insurance Upliftment 2  Invoice no:", kind: "ledger", formula: null, dbField: null },
  { index: 113, letter: "DJ", header: "Month", kind: "ledger", formula: null, dbField: null },
  { index: 114, letter: "DK", header: "MSSA Receipt no", kind: "ledger", formula: null, dbField: null },
  { index: 115, letter: "DL", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 116, letter: "DM", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 117, letter: "DN", header: "Outstanding", kind: "formula", formula: "DL{R}-DM{R}", dbField: null },
  { index: 118, letter: "DO", header: "Profit", kind: "ledger", formula: null, dbField: null },
  { index: 119, letter: "DP", header: "Remarks", kind: "field", formula: null, dbField: "notes" },
  { index: 120, letter: "DQ", header: "Done", kind: "ledger", formula: null, dbField: null },
];

export const ALPHA_COLUMNS: MasterColumn[] = [
  { index: 0, letter: "A", header: "Stock Nosuzu", kind: "field", formula: null, dbField: "stock_number" },
  { index: 1, letter: "B", header: "Claim No", kind: "field", formula: null, dbField: "claim_number" },
  { index: 2, letter: "C", header: "Insurance Company", kind: "field", formula: null, dbField: "insurance_company" },
  { index: 3, letter: "D", header: "Month", kind: "ledger", formula: null, dbField: null },
  { index: 4, letter: "E", header: "Date", kind: "field", formula: null, dbField: "loss_date" },
  { index: 5, letter: "F", header: "Claims Handler", kind: "field", formula: null, dbField: "claims_handler" },
  { index: 6, letter: "G", header: "Salvage Clerk", kind: "field", formula: null, dbField: "salvage_clerk" },
  { index: 7, letter: "H", header: "Make", kind: "field", formula: null, dbField: "make" },
  { index: 8, letter: "I", header: "Model", kind: "field", formula: null, dbField: "model" },
  { index: 9, letter: "J", header: "CC", kind: "field", formula: null, dbField: "engine_capacity_cc" },
  { index: 10, letter: "K", header: "Year", kind: "field", formula: null, dbField: "year" },
  { index: 11, letter: "L", header: "Keys", kind: "field", formula: null, dbField: "keys_status" },
  { index: 12, letter: "M", header: "Vin Number", kind: "field", formula: null, dbField: "vin_number" },
  { index: 13, letter: "N", header: "Engine Number", kind: "field", formula: null, dbField: "engine_number" },
  { index: 14, letter: "O", header: "Number Plate", kind: "field", formula: null, dbField: "registration_number" },
  { index: 15, letter: "P", header: "Write Off code", kind: "field", formula: null, dbField: "write_off_code" },
  { index: 16, letter: "Q", header: "Retail Value", kind: "field", formula: null, dbField: "retail_value" },
  { index: 17, letter: "R", header: "% Amount", kind: "formula", formula: "Q{R}*32%", dbField: null },
  { index: 18, letter: "S", header: "Date INV request", kind: "ledger", formula: null, dbField: null },
  { index: 19, letter: "T", header: "Salvage sold TAT", kind: "formula", formula: "NETWORKDAYS(E{R},S{R})", dbField: null },
  { index: 20, letter: "U", header: "IUM Inv No", kind: "field", formula: null, dbField: "insurance_invoice_no" },
  { index: 21, letter: "V", header: "IUM Amount", kind: "field", formula: null, dbField: "insurance_amount" },
  { index: 22, letter: "W", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 23, letter: "X", header: "Outstanding", kind: "formula", formula: "V{R}-W{R}", dbField: null },
  { index: 24, letter: "Y", header: "Date Paid", kind: "ledger", formula: null, dbField: null },
  { index: 25, letter: "Z", header: "Month Paid", kind: "ledger", formula: null, dbField: null },
  { index: 26, letter: "AA", header: "MSSA Profit", kind: "formula", formula: "AJ{R}-R{R}", dbField: null },
  { index: 27, letter: "AB", header: "Natis Docs", kind: "ledger", formula: null, dbField: null },
  { index: 28, letter: "AC", header: "Natis Received", kind: "ledger", formula: null, dbField: null },
  { index: 29, letter: "AD", header: "Ins Paid", kind: "ledger", formula: null, dbField: null },
  { index: 30, letter: "AE", header: "Status", kind: "field", formula: null, dbField: "status" },
  { index: 31, letter: "AF", header: "Transport", kind: "field", formula: null, dbField: "estimator_cost" },
  { index: 32, letter: "AG", header: "Store", kind: "field", formula: null, dbField: "current_location" },
  { index: 33, letter: "AH", header: "Arrival Date", kind: "field", formula: null, dbField: "arrival_date" },
  { index: 34, letter: "AI", header: "Collect TAT", kind: "formula", formula: "NETWORKDAYS(E{R},AH{R})", dbField: null },
  { index: 35, letter: "AJ", header: "Not Sold Amount", kind: "ledger", formula: null, dbField: null },
  { index: 36, letter: "AK", header: "Sold To", kind: "field", formula: null, dbField: "sold_to" },
  { index: 37, letter: "AL", header: "Selling Amount", kind: "field", formula: null, dbField: "selling_amount" },
  { index: 38, letter: "AM", header: "Deposit", kind: "ledger", formula: null, dbField: null },
  { index: 39, letter: "AN", header: "Total outstanding", kind: "formula", formula: "AL{R}-AM{R}", dbField: null },
  { index: 40, letter: "AO", header: "INV No", kind: "ledger", formula: null, dbField: null },
  { index: 41, letter: "AP", header: "Receipt 1", kind: "ledger", formula: null, dbField: null },
  { index: 42, letter: "AQ", header: "Receipt 2", kind: "ledger", formula: null, dbField: null },
  { index: 43, letter: "AR", header: "Receipt 3", kind: "ledger", formula: null, dbField: null },
  { index: 44, letter: "AS", header: "Receipt 4", kind: "ledger", formula: null, dbField: null },
  { index: 45, letter: "AT", header: "Purchase Agreement", kind: "ledger", formula: null, dbField: null },
  { index: 46, letter: "AU", header: "Release Creditor Invoice 1", kind: "ledger", formula: null, dbField: null },
  { index: 47, letter: "AV", header: "Invoice no", kind: "ledger", formula: null, dbField: null },
  { index: 48, letter: "AW", header: "Inv Date", kind: "ledger", formula: null, dbField: null },
  { index: 49, letter: "AX", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 50, letter: "AY", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 51, letter: "AZ", header: "Outstanding", kind: "formula", formula: "AX{R}-AY{R}", dbField: null },
  { index: 52, letter: "BA", header: "Release Creditor Invoice 2", kind: "ledger", formula: null, dbField: null },
  { index: 53, letter: "BB", header: "Invoice no", kind: "ledger", formula: null, dbField: null },
  { index: 54, letter: "BC", header: "Inv Date", kind: "ledger", formula: null, dbField: null },
  { index: 55, letter: "BD", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 56, letter: "BE", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 57, letter: "BF", header: "Outstanding", kind: "ledger", formula: null, dbField: null },
  { index: 58, letter: "BG", header: "IUM Release  Invoice no 1:", kind: "ledger", formula: null, dbField: null },
  { index: 59, letter: "BH", header: "RCP no", kind: "ledger", formula: null, dbField: null },
  { index: 60, letter: "BI", header: "Month", kind: "ledger", formula: null, dbField: null },
  { index: 61, letter: "BJ", header: "IUM Order no", kind: "ledger", formula: null, dbField: null },
  { index: 62, letter: "BK", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 63, letter: "BL", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 64, letter: "BM", header: "Outstanding", kind: "formula", formula: "BK{R}-BL{R}", dbField: null },
  { index: 65, letter: "BN", header: "IUM Release   Invoice no 2:", kind: "ledger", formula: null, dbField: null },
  { index: 66, letter: "BO", header: "RCP no", kind: "ledger", formula: null, dbField: null },
  { index: 67, letter: "BP", header: "Month", kind: "ledger", formula: null, dbField: null },
  { index: 68, letter: "BQ", header: "IUM Order no", kind: "ledger", formula: null, dbField: null },
  { index: 69, letter: "BR", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 70, letter: "BS", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 71, letter: "BT", header: "Outstanding", kind: "ledger", formula: null, dbField: null },
  { index: 72, letter: "BU", header: "Uplift Creditor 1", kind: "ledger", formula: null, dbField: null },
  { index: 73, letter: "BV", header: "Invoice no", kind: "ledger", formula: null, dbField: null },
  { index: 74, letter: "BW", header: "Inv Date", kind: "ledger", formula: null, dbField: null },
  { index: 75, letter: "BX", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 76, letter: "BY", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 77, letter: "BZ", header: "Outstanding", kind: "formula", formula: "BX{R}-BY{R}", dbField: null },
  { index: 78, letter: "CA", header: "Uplift Creditor 2", kind: "ledger", formula: null, dbField: null },
  { index: 79, letter: "CB", header: "Invoice no", kind: "ledger", formula: null, dbField: null },
  { index: 80, letter: "CC", header: "Inv Date", kind: "ledger", formula: null, dbField: null },
  { index: 81, letter: "CD", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 82, letter: "CE", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 83, letter: "CF", header: "Outstanding", kind: "formula", formula: "CD{R}-CE{R}", dbField: null },
  { index: 84, letter: "CG", header: "MSSA Upliftment 1  Invoice no:", kind: "ledger", formula: null, dbField: null },
  { index: 85, letter: "CH", header: "Month", kind: "ledger", formula: null, dbField: null },
  { index: 86, letter: "CI", header: "Invoice no", kind: "ledger", formula: null, dbField: null },
  { index: 87, letter: "CJ", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 88, letter: "CK", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 89, letter: "CL", header: "Outstanding", kind: "ledger", formula: null, dbField: null },
  { index: 90, letter: "CM", header: "MSSA Upliftment 2  Invoice no:", kind: "ledger", formula: null, dbField: null },
  { index: 91, letter: "CN", header: "Month", kind: "ledger", formula: null, dbField: null },
  { index: 92, letter: "CO", header: "Invoice no", kind: "ledger", formula: null, dbField: null },
  { index: 93, letter: "CP", header: "Amount", kind: "ledger", formula: null, dbField: null },
  { index: 94, letter: "CQ", header: "Paid", kind: "ledger", formula: null, dbField: null },
  { index: 95, letter: "CR", header: "Outstanding", kind: "ledger", formula: null, dbField: null },
  { index: 96, letter: "CS", header: "Profit", kind: "ledger", formula: null, dbField: null },
  { index: 97, letter: "CT", header: "Stock Take", kind: "ledger", formula: null, dbField: null },
  { index: 98, letter: "CU", header: "Old Cost code", kind: "ledger", formula: null, dbField: null },
  { index: 99, letter: "CV", header: "Collected Natis", kind: "ledger", formula: null, dbField: null },
  { index: 100, letter: "CW", header: "Remarks", kind: "field", formula: null, dbField: "notes" },
  { index: 101, letter: "CX", header: "Done", kind: "ledger", formula: null, dbField: null },
];
